Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================ RESTART: C:\Users\WINDOWS11\Desktop\pratice.py ================
input1 [4, 5, 1, 2, 3]
input2 [1, 2, 3, 4, 5]
input3 [2, 3, 4, 5, 1]
Traceback (most recent call last):
  File "C:\Users\WINDOWS11\Desktop\pratice.py", line 30, in <module>
    input1 [4, 5, 1, 2, 3]
NameError: name 'input1' is not defined. Did you mean: 'input'?
>>> 
================ RESTART: C:\Users\WINDOWS11\Desktop\pratice.py ================
input1 [4, 5, 1, 2, 3]
input2 [1, 5, 4, 3, 2]
input3 [3, 4, 5, 1, 2]
Traceback (most recent call last):
  File "C:\Users\WINDOWS11\Desktop\pratice.py", line 34, in <module>
    input1 [4, 5, 1, 2, 3]
NameError: name 'input1' is not defined. Did you mean: 'input'?
>>> 
================ RESTART: C:\Users\WINDOWS11\Desktop\pratice.py ================
input1 [4, 5, 1, 2, 3]
input2 [1, 5, 4, 3, 2]
input3 [3, 4, 5, 1, 2]
